### ISSUE TITLE
Inline swagger spec inside of template file not working for multiple paths

### ISSUE THREAD

**Issue by talhasavo** [awslabs/serverless-application-model#99] opened 2017-02-27 22:16 UTC
**Summary:**
Given that a deploy and API gateway stack exist for one path, updating the API gateway inline swagger definition with a second path breaks Cloudformation command execution. In particular, if the first path is a subset of the second one. 

**Details:**
I have an inline swagger spec inside of a template.yaml file.

I run the following command:  
aws cloudformation deploy --template-file deploy.yaml --stack-name my-api-stack --capabilities CAPABILITY_IAM

Steps: 
1. Command successfully creates a new stack my-api-stack when template has only one path /thing .  
2. Now we modify inline swagger spec in the template.yaml to add a second endpoint /thing/{id}/anotherthing. We run the aws command again. Adding the second path /thing/{id}/asset breaks SAM execution. 

Error: **ResourceStatusReason': 'Invalid Authorizer identifier specified**

The error seems a red herring. The authorizer lambda exists and works fine when one path is included.

I also validated my swagger by manually creating the API Gateway endpoint and exporting its spec, and it is identical to what I am providing to SAM. 

template:yaml
----------------
ApiGatewayApi:
      Type: AWS::Serverless::Api
      DependsOn: lambda1,lambda2
      Properties:
        StageName: prod
        DefinitionBody:
           [Inline Swagger]

I include the following inline swagger spec with two paths: 
Inline swagger: 
---------------
swagger: "2.0"
info:
  version: "2017-02-27T20:31:23Z"
  title: "test-rb"
basePath: "/prod"
schemes:
\- "https"
paths:
  /thing:
    get:
      responses: {}
      security:
      - auth_this: []
      x-amazon-apigateway-integration:
        uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambda1/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  /thing/{id}/anotherthing:
    get:
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:{}
      security:
      - auth_this: []
      x-amazon-apigateway-integration:
        uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambda2/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
securityDefinitions:
  auth_this:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
    x-amazon-apigateway-authorizer:
      authorizerResultTtlInSeconds: 300
      authorizerUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:customauthorizer/invocations"
      type: "token"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"

**Comment by jaredhagen** [comment] 2017-03-12 22:09
I've ran into this issue a couple of times now I've found that if you create the resources through the console first subsequent stack updates succeed.

**Comment by brunomorency** [comment] 2017-03-29 03:05
I get the same error whenever I had a resource/method that uses an existing custom authorizer that deploys with no problems.

**Comment by gtaws** [comment] 2017-04-02 01:22
I've gotten similar and the workaround I had to do is to double-quote all my paths in the transformed SAM yaml template.

**Comment by dinvlad** [comment] 2017-04-04 23:45
Same problem here. Deploying a new method with an existing custom authorizer (that works well for existing methods) leads to `Invalid Authorizer identifier specified`

**Comment by mgibas** [comment] 2017-04-12 19:04
Same issue here - very annoying when we try to merge our development branch to production :disappointed:

**Comment by 8357753** [comment] 2017-04-19 01:36
Yep same error for me too. Means SAM is not very useful for production :(

**Comment by brunomorency** [comment] 2017-04-19 14:38
@dinvlad the 2-step commit is really annoying when deploying to production. Rather than just pulling/merging changes to the template then deploying, you'd now need to do manually repeat those steps or start keeping multiple versions of the template in the repo and get some script to replay those steps from current production version to newest found in repo.

I've had to maintain db schemas like that and it much rather have this bug fixed than having to deal with similar setup with templates :(

Unless you have another way to do it?

**Comment by 8357753** [comment] 2017-04-19 18:46
We have 5 environments to support, two dev which integrate automatic commits and then manual promotion to test -> uat -> prod. Pushing fake leading commits to all these environments will cause lots of false positive test failures in our automatic test suite.

**Comment by dinvlad** [comment] 2017-04-19 19:56
@brunomorency I can relate to that, though I do continuous delivery instead of deployment, so not every change makes it into production.

Also, if you use the OPTIONS method then there's no compromise - you first fully configure this method, and then add additional ones (GET/POST/...) with full configuration.

In addition, making small changes is almost always better than too many things at once..

**Comment by 8357753** [comment] 2017-04-19 20:53
Well sometimes the smallest change for us is adding the config with an authorizer because for some apis we do not use CORs and for other apis we use api gateway in proxy mode. So basically we need to add fake commits which is not optimal. We don't push all changes to production but they do all go to some subset of environments.

**Comment by dinvlad** [comment] 2017-04-20 00:07
Fair enough, though pushing into red should not be a problem :)

**Comment by 8357753** [comment] 2017-04-20 01:24
false positives are friction for us and in any case these are unnecessary builds which will cascade to various other integrations causing more false positives. Sure all this can the solved with various gymnastics but fixing the issue at source seems a better solution.

**Comment by dinvlad** [comment] 2017-04-20 16:01
Point taken. I agree that this issue leads to inconsistent/unexpected behavior (deployed API doesn't reflect what's in the spec) and should for sure be addressed.

**Comment by dinvlad** [comment] 2017-04-20 16:50
Point taken. I agree that this issue leads to inconsistent behavior, which on itself needs a fix.

**Comment by kskory** [comment] 2017-05-12 20:07
@sanathkr any update on that? Are you aware of that issue? It's pretty limiting and doesn't have any sensible workaround.

**Comment by lafiosca** [comment] 2017-05-17 20:32
I just ran into this as well. Was working on a new API, everything fine, until I added a second endpoint and it blew up. Thankfully Google led me to this issue, which I recalled reading about before and thinking, "Oh this will affect me later."

Thank you @dinvlad for the workaround, but I agree with everyone saying that this needs to be fixed. I don't want to do two consecutive deployments effectively just to add one new GET endpoint.

**Comment by lafiosca** [comment] 2017-05-17 20:54
I'll also confirm/reiterate that this only happens when updating an existing API. I was able to delete my entire API and redeploy without an error.

**Comment by dinvlad** [comment] 2017-06-09 21:00
I also agree after playing around with it more, that it's pretty annoying. Especially for changing existing routes (e.g. when renaming a path parameter).

**Comment by sanathkr** [comment] 2017-06-28 06:42
Yes, I am aware of this issue. We have a fix being implemented now. I don't have an ETA for the fix, but it is happening. Will keep this thread posted. Sorry for the annoyance :(

**Comment by kskory** [comment] 2017-07-11 20:02
Hey @sanathkr , any updates? Is there any "official" issue for that, where we can track the progress? I don't see anything here: https://github.com/aws/aws-cli/issues .

Thanks

**Comment by sanathkr** [comment] 2017-07-12 03:02
@kskory this is pretty much the only Issue tracking this.

**Comment by PutziSan** [comment] 2017-10-17 22:00
About 3 Months since last update: Are there any news?

**Comment by sanathkr** [comment] 2018-01-10 20:28
This bug is fixed now. Please check and re-open if you have questions.

**Closed by sanathkr** 2018-01-10 20:28 UTC
Labels: area/serverless-api, type/bug
