### ISSUE TITLE
Question on api_swagger_cors example

### ISSUE THREAD

**Issue by AlexOugh** [awslabs/serverless-application-model#47] opened 2016-12-26 17:44 UTC
After replacing <<region>> and <<account>>, I successfully created a stack for this example along with lambda invoke permissions, but when I test the api methods, it fails with a permission error even if I specify the lambda function name in 'Stage Variables -LambdaFunctionName'.

So I changed the target lambda function name from '${stageVariables.LambdaFunctionName}' to the real function name in the 'Integration Request' section and it works ok, but I don't think it is necessary.

So I'm wondering if I'm missing something.

**Comment by kylegalbraith** [comment] 2016-12-28 00:13
I am seeing the same problem in the example as well. The SAM template is giving a missing parameter exception saying the StageName was not specified, but when I do specify it, still get the same error.

**Comment by sanathkr** [comment] 2017-01-03 19:50
On API Gateway console, can you look under StageVariables tab for the value of LambdaFunctionName stage variable? This should be name of the Lambda function you created. [This link](http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-set-stage-variables-aws-console.html) will roughly tell you where the StageVariables tab is.

**Comment by AlexOugh** [comment] 2017-01-11 16:23
Yes, it has it. 
I think the issue is because the API doesn't have a permission to run the Lambda function, which is NOT in the swagger.yaml file.
Don't we need to add the permission in 'x-amazon-apigateway-integration' - 'credentials' in the swagger.yaml file?

**Comment by AlexOugh** [comment] 2017-01-19 14:51
I found the issue. It works well when I run it, but the problem is when you try to test it in the API Gateway console. You'll receive "internal error" because of no permission when you test the method.

I usually test it first before running it after deployment, so I didn't know it works when it runs. So maybe it will be better for you guys to fix this.

**Comment by sanathkr** [comment] 2018-01-10 19:51
Dupe of #59.

**Closed by sanathkr** 2018-01-10 19:51 UTC
