### ISSUE TITLE
Document usage of ${ServerlessRestApi}

### ISSUE THREAD

**Issue by matsev** [awslabs/serverless-application-model#222] opened 2017-12-05 09:29 UTC
Please document the the `${ServerlessRestApi}` CloudFormation pseudo parameter used in the [example project](https://github.com/awslabs/serverless-application-model/blob/3cda50ddf3d2823162438cc3c72277828a20125f/examples/2016-10-31/encryption_proxy/template.yaml#L17). 

A similar example:

```
Outputs:
  ServerUrl:
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
    Description: The url of the API Gateway
```

**Comment by jfuss** [comment] 2018-01-10 20:13
Duplicate of #251. Closing in favor of the Doc revamp. Also added "document generated LogicalIds" to that issue.

**Closed by jfuss** 2018-01-10 20:13 UTC
Labels: area/docs, type/documentation, type/duplicate
