### ISSUE TITLE
Feature Request: Option to delete failed stacks that roll back

### ISSUE THREAD

**Issue by mrichman** [awslabs/serverless-application-model#1534] opened 2020-03-25 17:50 UTC
When a stack rolls back to due a template error, you receive an error such as:

```
Error: Failed to create changeset for the stack: sam-app, An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-east-1:123456789012:stack/sam-app/ba941550-6ebe-11ea-a521-0e3283634b is in ROLLBACK_COMPLETE state and can not be updated.
```

The only way to clear this is to delete the stack in CloudFormation. A convenience function in the CLI would be very helpful here.

**Comment by jfuss** [comment] 2020-03-25 18:13
Duplicate of https://github.com/awslabs/aws-sam-cli/issues/1865

**Closed by jfuss** 2020-03-25 18:13 UTC
