### ISSUE TITLE
Changing an Api Event does not redeploy the API resource

### ISSUE THREAD

**Issue by jolexa** [awslabs/serverless-application-model#73] opened 2017-01-25 16:42 UTC
Here is my scenerio:

Deployed this:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  ExampleFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: test.lambda_handler
      Runtime: python2.7
      CodeUri: ./deployment.zip
      Description: "Test Function"
      MemorySize: 128
      Timeout: 3
      Policies:
        - Statement:
            Effect: Allow
            Action: "sns:Publish"
            Resource:
              - $test_arn1
              - $test_arn2
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /
            Method: get
```

Then I had to change the Method to `post` and redeployed. I found that I had to go into the AWS Console and manually deploy the API again. I do not think this is by design and perceived by me to be an oversight/bug. Thoughts?

**Comment by sanathkr** [comment] 2017-01-25 18:45
Sorry you ran into it. This is a bug that we are working on fixing soon

**Comment by sanathkr** [comment] 2017-01-25 19:05
Duplicate of #53

**Closed by sanathkr** 2017-01-25 19:05 UTC
Labels: bug
