### ISSUE TITLE
Globals/Api/BinaryMediaTypes is not honored when SAM template is updated and re-deployed

### ISSUE THREAD

**Issue by abhilash1in** [awslabs/serverless-application-model#561] opened 2018-09-05 14:09 UTC
**Description:**
`BinaryMediaTypes` is removed from APIGW settings when SAM template is updated and re-deployed

**Steps to reproduce the issue:**
1. Create a simple SAM application with `Globals` as follows:
```
Globals:
    Api:
        BinaryMediaTypes:
            - "*~1*"
```
2. Package and deploy. Observe `Settings` section of the new APIGW API. `Binary Media Types` will have `*/*`

3. Make some changes to the SAM template. Re-package and re-deploy. Observe `Settings` section of the APIGW API. `Binary Media Types` config is empty/missing

**Observed result:**
`Binary Media Types` config is empty/missing after SAM template is updated and redeployed

**Expected result:**
`Binary Media Types` does not change after stack update.

**Output of `sam --version`**: `SAM CLI, version 0.6.0`

**Optional Debug logs**:

`Add --debug flag to command you are running`

**Comment by jfuss** [comment] 2018-09-05 14:16
Closing as this does not relate to this project. I responded on the issue that was made to AWS SAM CLI.

**Comment by mrjomp** [comment] 2019-03-20 10:32
This needs to be reopened, it has not been fixed and it's part of the SAM templates

**Comment by keetonian** [comment] 2019-03-25 21:40
@mrjomp could you provide more details of what your error is and how you encountered it? Is it the exact same as the original post in this issue?

**Comment by emanuelhjertzen** [comment] 2019-04-27 21:49
Ran into this issue today also. Exactly as described in original description by @abhilash1in.
I first set to '*~1*' in template.yaml. Then changed to 'image~1png' and packages/deployed. After that the BinaryMediaTypes have been removed. Changing them further does not have any effect.

**Comment by emanuelhjertzen** [comment] 2019-04-27 22:07
Did further tests:
1. In template set 
BinaryMediaTypes:
  - image~1gif
  - image~1png
Package/deploy got the expected result.

2. Change template to
BinaryMediaTypes:
  - image~1gif
  - image~1png
  - application~1vnd.openxmlformats-officedocument.spreadsheetml.sheet
Package/deploy resulted in only application/1vnd.openxmlformats-officedocument.spreadsheetml.sheet set in console.

3. Change template to
BinaryMediaTypes:
  - image~1gif
  - image~1png
  - application~1vnd.openxmlformats-officedocument.spreadsheetml.sheet
  - image~1tiff
Package/deploy resulted in only image/tiff set in console

4. Change template to
BinaryMediaTypes:
  - image~1gif
  - image~1png
  - application~1vnd.openxmlformats-officedocument.spreadsheetml.sheet
  - image~1tiff
  - image~1jpeg
Package/deploy resulted in only image/jpeg set in console

**Comment by brianleroux** [comment] 2019-05-16 21:07
Also encountering this error. We are currently working around it by manually updating in the console and deploying the api manually. Not ideal!

**Comment by ashishusoni** [comment] 2019-05-20 21:14
Is this resolve yet .. i am facing the same issue

**Comment by brianleroux** [comment] 2019-05-21 19:21
I have created an example with steps to reliably reproduce the behavior. It looks like anything that results in updating the deployment of apigateway will remove the binary media types. 

https://github.com/brianleroux/cloudformation-update-stack-removes-binary-media-types

**Comment by brettstack** [comment] 2019-05-24 19:46
This is an API Gateway/CloudFormation issue. I've contacted the teams internally.

**Comment by brettstack** [comment] 2019-05-28 22:07
SAM can resolve this by changing the way we set `BinaryMediaTypes`. Instead of setting it as a property of the CloudFormation Resource, we will need to set it via Swagger/OpenApi `x-amazon-apigateway-binary-media-types`

**Comment by brettstack** [comment] 2019-06-07 16:56
PR for fixing BinaryMediaTypes getting lost in update #954

**Comment by praneetap** [comment] 2019-07-26 19:59
Released with v1.13.0

**Closed by praneetap** 2019-07-26 19:59 UTC
Labels: stage/waiting-for-release, type/bug

**Comment by burritoIand** [comment] 2020-03-17 00:02
just ran into this, although I'm using strictly cloudformation templates with the sam transform. Should I not be seeing this problem? I made a change to `BinaryMediaTypes` and upon committing/updating my stack, and then inspecting cloudfront distro in the web console, the BinaryMediaTypes are empty

**Comment by keetonian** [comment] 2020-03-17 18:12
@burritoIand we encountered a problem where we were setting BinaryMediaTypes in the CloudFormation property, but should have been setting them in the Swagger/OpenApi document. This resulted in a behavior where on first deployment, the BinaryMediaTypes were present, but then would be removed when we updated the API.

If you are using Swagger/OpenApi, make sure to add the BinaryMediaTypes inside of your Swagger/OpenApi API definition.

**Comment by ambareng** [comment] 2023-10-08 15:09
@keetonian still have this issue in 2023 setting BinaryMediaTypes in Globals still does not work, it kind of did at first but when I tried to update/replicate it wasn't updating anymore, I'm not using OpenAPI/Swagger API this is for AWS::Serverless::Api SAM
