### ISSUE TITLE
VpcConfig leaves behind Network Interface

### ISSUE THREAD

**Issue by joekiller** [awslabs/serverless-application-model#64] opened 2017-01-19 17:24 UTC
When I create a stack that uses the VpcConfig (hard coded due to #22) and then go to delete the stack the resulting ENI that is created to enable the VpcConfig isn't deleted so when I go to delete the database and it's security group, the security group cannot be deleted due to the lingering lambda function's ENI.

As a user, when I delete a `AWS::Serverless::Function` with a `VpcConfig` specified the ENI should be deleted as well.

**Comment by sanathkr** [comment] 2017-01-25 19:46
Did you create the security groups outside of the template? CloudFormation cannot delete resources create outside of the template. You have to do it manually until the bug is fixed

**Comment by joekiller** [comment] 2017-01-26 03:54
Yes they were created outside of the stack due to the #57

**Comment by sanathkr** [comment] 2017-01-26 18:27
Yeah, then CloudFormation won't delete those resources. This is by design to let CloudFormation manage only resources that it creates

**Comment by joekiller** [comment] 2017-01-26 18:47
Okay I'll try creating a SG and ingress rule on the existing SG in the template and see if the ENI gets deleted. Of course #57 might still prevent this.

**Comment by sanathkr** [comment] 2017-01-26 20:48
Yes, #57 is on the works. It should prevent your problem. I am closing this issue for now.

**Comment by dinvlad** [comment] 2017-02-17 01:46
The problem comes even when some "external" resources (e.g. subnets) are created via a custom resource in the same stack, e.g.
```
VpcConfig:
  SubnetIds: !GetAtt CustomSubnets.SubnetIds
  ...
```
Here my `CustomSubnets` resource creates a few subnets and exports their IDs via `SubnetIds`. The attribute gets resolved correctly (!), and Lambda is created successfully.

When I delete the stack, since this Lambda references `CustomSubnets`, it should be deleted before the latter, and then `CustomSubnets` would handle `Delete` request successfully by deleting associated subnets.

However, upon deletion the `Delete` request complains that its subnets are still associated with the Lambda's ENI. So there's no way to cleanly delete the stack.

**Comment by sanathkr** [comment] 2017-02-17 22:22
Did you give your Lambda permission to delete the ENI? Checkout - http://docs.aws.amazon.com/lambda/latest/dg/vpc.html

**Comment by dinvlad** [comment] 2017-02-17 23:47
Yes, it is assigned `AWSLambdaVPCAccessExecutionRole`

**Comment by dinvlad** [comment] 2017-02-17 23:54
Cool, it's working correctly after today's intrinsic fix. Thanks!

**Closed** 2017-02-20 18:29 UTC
Labels: question
