### ISSUE TITLE
SAM Template AWS API GW logging.

### ISSUE THREAD

**Issue by senthil-nathan** [awslabs/serverless-application-model#100] opened 2017-02-28 00:35 UTC
I am using SAM Template to create API GW that would hook to a lambda function.  Is there a way that I can specify the logs to be enabled for the stages ? Right now after the deploy I need to manually enable logs in the UI which is bit annoying.

**Comment by anotherhobby** [comment] 2017-03-02 16:15
We are looking for this same functionality.

**Comment by terodox** [comment] 2017-05-09 17:12
This is a miss from my perspective.  Every deployment actually disables logging even if it was previously enabled.

Do we have any idea of a timeline for this to be addressed?

**Comment by sanathkr** [comment] 2017-06-28 06:49
Makes sense. This is a popular feature ask. I will work to get this work prioritized.

**Comment by jonmcewen** [comment] 2017-07-04 09:52
+1

**Comment by digitalfiz** [comment] 2017-07-13 16:54
+1

**Comment by CrazyBS** [comment] 2017-08-23 23:27
+1

**Comment by manikandanrs** [comment] 2017-09-19 19:25
+1

**Comment by hasansaghir** [comment] 2017-09-25 01:42
+1

**Comment by bradleyjames** [comment] 2017-10-17 13:49
I've been told the only way to do this in an automated fashion via CFN is to not use SAM to define the API and stage.  Feels like this violates the core tenet from [CONTRIBUTING.md](https://github.com/awslabs/serverless-application-model/blob/master/CONTRIBUTING.md):

```
When defining your feature, keep in mind that one of the core tenets of AWS SAM is to keep it easy to use while allowing customers access to use more advanced components, should they so choose.
```

Access to more advanced components shouldn't be manual work in the console.  This is more of a general comment but the more I use SAM, and the closer I get to production, the less I feel I can actually use it because it misses on simple things... like logging.

To ensure my deployments are repeatable I may just try to script this after my CFN templates are deployed.

**Comment by jfuss** [comment] 2017-10-17 22:53
@bradleyjames We are aware this is currently painful and are currently working on this feature. However, it is stuck in some discussions on how to move forward on part of the design. We do not have a date yet, but will reply here once we have something to share.

Please be patient with us as we sort some things out internally.

**Comment by bradleyjames** [comment] 2017-10-23 12:50
For anyone looking for a workaround I went ahead and scripted this.  The template that creates the API outputs the ApiId at "AwsApiId".

```yaml
...
Outputs:
  AwsApiId:
    Value: !Ref AwsApi
    Export:
      Name: !Sub ${AWS::StackName}-AwsApiId
```

After standing up the stack...

```bash
API_ID=`aws cloudformation describe-stacks --stack-name $STACK_NAME | jq '.Stacks[0].Outputs[] | select(.OutputKey == "AwsApiId") | .OutputValue' -r`

# http://docs.aws.amazon.com/cli/latest/reference/apigateway/update-stage.html
aws apigateway update-stage --rest-api-id $API_ID --stage-name  $STAGE_NAME --patch-operations \
  op=replace,path=/*/*/logging/dataTrace,value=true \
  op=replace,path=/*/*/logging/loglevel,value=Info \
  op=replace,path=/*/*/metrics/enabled,value=true 
```

**Comment by s83** [comment] 2017-10-25 09:55
@bradleyjames thank you for workaround!

a little improvement, you can use `--query` to extract the API_ID

```
API_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`AwsApiId`].OutputValue --output text)
```

**Comment by jfuss** [comment] 2018-01-08 20:13
We created a parent task to track this. Please see #248 for updates.

Closing as duplicate of #248

**Closed by jfuss** 2018-01-08 20:13 UTC
Labels: type/duplicate, type/feature

**Comment by CGick** [comment] 2019-12-03 19:05
To enable the CloudWatch Logs for AWS::Serverless::Api, you can set the LoggingLevel in the MethodSettings property.
```
Type: AWS::Serverless::Api
    Properties:
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: '/*' # allows for logging on any resource
          HttpMethod: '*' # allows for logging on any method
```

**Comment by LeonardoX77** [comment] 2023-02-13 15:07
> To enable the CloudWatch Logs for AWS::Serverless::Api, you can set the LoggingLevel in the MethodSettings property.
> 
> Type: AWS::Serverless::Api
>     Properties:
>       MethodSettings:
>         - LoggingLevel: INFO
>           ResourcePath: '/*' # allows for logging on any resource
>           HttpMethod: '*' # allows for logging on any method
> 

I think that's not enough, cause I get an error `CloudWatch Logs role ARN must be set in account settings to enable logging`. I solved adding a role that is using a `AmazonAPIGatewayPushToCloudWatchLogs` policy:

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    DependsOn: ApiCWLRoleArn
    Properties:
      StageName: prod
      MethodSettings:
        - LoggingLevel: INFO
          MetricsEnabled: True
          ResourcePath: '/*' # allows for logging on any resource
          HttpMethod: '*' # allows for logging on any method
      Auth:
        ApiKeyRequired: true # sets for all methods

  ApiCWLRoleArn:
    Type: AWS::ApiGateway::Account
    Properties: 
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

# IAM Role for API Gateway + CloudWatch Logging
  CloudWatchRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Path: /
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'
