### ISSUE TITLE
Invalid permissions on Lambda function

### ISSUE THREAD

**Issue by jagu-sayan** [awslabs/serverless-application-model#296] opened 2018-02-12 14:50 UTC
### Description
I got an `Invalid permissions on Lambda function` when I try to invoke my lambda function from API Gateway.

In fact SAM generate this invalid arn in API Gateway Lambda trigger :
![image](https://user-images.githubusercontent.com/1262860/36101957-168eb96a-100b-11e8-9b75-a6cf43977f34.png)

`ANY` is not valid in this arn.
Reference: [Resource Format of Permissions for Executing API in API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html#api-gateway-iam-policy-resource-format-for-executing-api)

This notation is the same than [API swagger cors example](https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/template.yaml)

Related to:
- https://stackoverflow.com/questions/41817075/cloudformation-invalid-permissions-on-lambda-function#41819244
- http://www.1strategy.com/blog/2017/06/06/how-to-use-amazon-api-gateway-proxy/

### Example
```yaml
Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: "Contact API"
          version: "v0.1.0"
        host: "https://example.com"
        basePath: "/"
        schemes:
          - https
        paths:
          "/{proxy+}":
            x-amazon-apigateway-any-method:
              x-amazon-apigateway-integration:
                # https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
              consumes:
                - application/json
              produces:
                - application/json
              parameters:
                - name: proxy
                  in: path
                  required: true
                  type: string
              responses:
                "200":
                  schema:
                    $ref: '#/definitions/Empty'
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "ExampleFunction"
      Handler: main.handler
      Runtime: nodejs6.10
      MemorySize: 512 # 512 Mo
      CodeUri: ../dist
      Events:
        SendEmailEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY
      Policies:
        - SESCrudPolicy:
            IdentityName: contact@example.com
```

### Workaround:
```yaml
      Events:
        SendEmailEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: "*"  # Use '*' instead of ANY
```

CC @yvele

**Comment by jfuss** [comment] 2018-02-12 16:11
Duplicate of #59, therefore closing

Calling the endpoint (http requests) outside of the 'Test Button' on the console works. We are aware of the issue and are working on getting a fix out.

**Closed by jfuss** 2018-02-12 16:11 UTC
