### ISSUE TITLE
No multiple stage creation mechanism is there in AWS:Serverless::Api resource type

### ISSUE THREAD

**Issue by arcsoftech** [awslabs/serverless-application-model#435] opened 2018-05-15 11:27 UTC
There is no provision to create multiple stage for the same api gateway in same model.And when we create manual stages from console then it give lambda invocation error.

**Comment by brettstack** [comment] 2018-06-27 03:32
Duplicate of #198

**Closed by brettstack** 2018-06-27 03:32 UTC
