### ISSUE TITLE
TableName for AWS::Serverless::SimpleTable

### ISSUE THREAD

**Issue by xiangshen-dk** [awslabs/serverless-application-model#155] opened 2017-07-01 13:26 UTC
Can we have TableName for AWS::Serverless::SimpleTable?

**Comment by sanathkr** [comment] 2017-07-01 19:57
Yes this is already in the works. Should be out shortly

**Comment by sanathkr** [comment] 2017-07-01 19:58
Duplicate of #112

**Closed by sanathkr** 2017-07-01 19:58 UTC
Labels: feature-request

**Comment by mnwk** [comment] 2018-01-03 14:34
no this reference to 122 i a loop
