### ISSUE TITLE
Execution failed due to configuration error: Lambda was not able to access EC2's API using the Lambda Execution Role to set up the Lambda function

### ISSUE THREAD

**Issue by wes3985** [awslabs/serverless-application-model#1074] opened 2019-08-08 14:35 UTC
I'm not sure if this is a bug or just a lack of 'complete' examples to template from in the docs. I am seeing the above error with AWS SAM CLI when deploying lambdas through cloud formation. The following yaml works:

```
Globals:
  Function:
    Timeout: 750
    VpcConfig:
      SecurityGroupIds: 
        - sg-xxxx
      SubnetIds: 
       - subnet-1
       - subnet-2
Resources:
   MyFunction:
     Type: AWS::Serverless::Function 
     Properties: 
        CodeUri: src/
        Handler: MyFunction.lambda_handler 
        Policies:
        - Statement:
            Sid: "ec2resources"
            Effect: Allow
            Action: 
              - "ec2:CreateNetworkInterface"
              - "ec2:AttachNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DetachNetworkInterface"
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeSubnets"
              - "ec2:DescribeVpcs"
            Resource:
              - "*"
```

The following throws the error even through the subnets and security groups are identical to those in the globals configuration:

```
        .......
        - Statement:
            Sid: "ec2resources"
            Effect: Allow
            Action: 
              - "ec2:CreateNetworkInterface"
              - "ec2:AttachNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DetachNetworkInterface"
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeSubnets"
              - "ec2:DescribeVpcs"
            Resource:
              - "arn:aws:ec2:eu-west-1:acc:security-group/sg-xxxx"
              - "arn:aws:ec2:eu-west-1:acc:subnet/subnet-1"
              - "arn:aws:ec2:eu-west-1:acc:subnet/subnet-2"
              - "arn:aws:ec2:eu-west-1:acc:network-interface/*"
              - "arn:aws:ec2:eu-west-1:acc:vpc/vpc-xyz"
```

Is it possible I am missing a permission? Or a resource from the policy?

**Comment by roryj** [comment] 2019-08-13 21:32
Hi @wes3985, unfortunately what you are trying to do is not currently possible. Looking at the [Actions, Resources, and Condition Keys for Amazon EC2](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonec2.html) documentation none of those actions support specifying a specific resource. 

Out of curiosity, what was the exact error you were seeing?

**Comment by wes3985** [comment] 2019-08-14 12:42
Hi Rory,

Thanks for getting back to me. Ah I see, I've redeployed it with '*' as the
resource, and that explains why it now works.

We were advised from a security perspective to only allow specific
resources as part of policies so that the lambda is limited in what it can
access. For instance the S3 policy for this lambda can only access a
specific bucket. We wanted the ec2 to only be within our vpc and subnets.
Are there plans to allow this functionality in the future? Or have I
misunderstood aspects of how/why the yaml is laid out like this?

This error was thrown on the AWS console when I was testing the lambda. The
lambda itself didn't actually run due to this error so there is no
cloudwatch log, only this message on the console.

Let me know if there is anything else I can provide.

Many thanks,

Wes

**Comment by chrisoverzero** [comment] 2019-08-14 16:54
The thing here is that IAM is typically a _resource-based_ authentication system.

Let's look at the permission `ec2:CreateNetworkInterface`. What resource would it be associated with? The network interface it hasn't yet created. So permissions like those are [associated with][] the resource `*`. Similarly, the permission `ec2:AttachNetworkInterface`. What resource? The one which will be created after launch, for which there's no accessible identifier at deployment time.

The SAM team has created a [Policy Template][] which wraps all this up, though. It's called "VPCAccessPolicy". It takes the meaningful policies you specified above and turns them into this:

```yaml
Policies:
- VPCAccessPolicy: {}
```

You can find [its expansion][] here in the repo, to check for yourself.

> We wanted the lambda to only run within our vpc and subnets.

The way to do this is exactly as you already have, the `VpcConfig`. This is a problem solved by configuration, not permission.

[associated with]: https://iam.cloudonaut.io/reference/ec2/CreateNetworkInterface.html
[Policy Template]: https://github.com/awslabs/serverless-application-model/blob/master/docs/policy_templates.rst
[its expansion]: https://github.com/awslabs/serverless-application-model/blob/0f1a0823546acc7369a9059de302bcac4267d2eb/samtranslator/policy_templates_data/policy_templates.json#L573-L592

**Comment by jlhood** [comment] 2019-08-14 23:17
@chrisoverzero's explanation is spot on. Closing this issue since SAM and Lambda are working as intended.

**Closed by jlhood** 2019-08-14 23:17 UTC
