### ISSUE TITLE
Troubleshoot cfn 'Internal Failure'

### ISSUE THREAD

**Issue by grittershub** [awslabs/serverless-application-model#195] opened 2017-09-11 07:42 UTC
I'm trying to build a mock API using inline swagger. This is to support an pre-flight OPTIONS request using an Authorization header, so it needs cors enabled.
I created it manually with API gateway and it works. I then exported it from the API gateway in yaml format. When I put it into template.yml in my codestar project, it fails silently inside the deploy phase with an 'Internal Failure'. Is there any way I can troubleshoot this to work out what is in fact causing the failure?

Below is the template.yml I'm trying to deploy, the DefinitionBody is literal paste of the working API gateway YAML export. When I try to run this through cfn at the command line, it gives me a
An error occurred (ValidationError) when calling the CreateChangeSet operation: Template format error: [/Resources/MyApiOptions/Properties/DefinitionBody/paths//myapi/query/options/responses] map keys must be strings; received numeric [200] instead
Changing the responses 200: to '200': now gets me straight back to 'Internal Failure'

```
            "ResourceStatus": "UPDATE_ROLLBACK_IN_PROGRESS", 
            "ResourceType": "AWS::CloudFormation::Stack", 
            "Timestamp": "2017-09-11T09:17:50.141Z", 
            "ResourceStatusReason": "Internal Failure", 
```
Template:

```
AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Resources:
  MyApiOptions:
    Type: AWS::Serverless:Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "1.0"
          title: "awscodestar-ot-py-lambda"
        host: "myhostname"
        schemes:
        - "https"
        paths:
          /myapi/query:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/$MYARN/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws_proxy"
            options:
              consumes:
              - "application/json"
              responses:
                200:
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Request-Headers:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Authorization'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                      method.response.header.Access-Control-Request-Headers: "'Authorization'"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                passthroughBehavior: "when_no_match"
                type: "mock"
```

**Comment by dslagle** [comment] 2017-12-07 14:47
This is old, but for anyone landing here, I believe the issue is a missing colon in the resource type name.
```yaml
MyApiOptions:
    Type: AWS::Serverless:Api
```
There is a missing colon between Serverless and Api. I recently ran into this issue myself, and after meticulously scouring the document, managed to find my missing colon. After adding the colon back, everything worked as expected.

**Comment by sanathkr** [comment] 2018-01-12 21:32
Closing this because there is nothing much to do on the SAM service. [SAM Local CLI](https://github.com/awslabs/aws-sam-local) validate command would help you catch this.

**Closed by sanathkr** 2018-01-12 21:32 UTC
