### ISSUE TITLE
ReservedConcurrentExecutions from SAM

### ISSUE THREAD

**Issue by rbbhar** [awslabs/serverless-application-model#277] opened 2018-01-31 19:08 UTC
Is there a way to set `ReservedConcurrentExecutions` from the SAM template?
I see that it can be set in the normal cloudformation script - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-reservedconcurrentexecutions.

**Comment by jfuss** [comment] 2018-01-31 19:09
Duplicate of #265

**Comment by rbbhar** [comment] 2018-01-31 19:10
@jfuss - Sorry, didn't find that link. Thanks for the update.

**Closed by jfuss** 2018-01-31 19:09 UTC
Labels: type/duplicate

**Comment by jfuss** [comment] 2018-01-31 19:15
@rbbhar Not an issue at all. :)
