### ISSUE TITLE
Create multiple stages in one api resource

### ISSUE THREAD

**Issue by bluedusk** [awslabs/serverless-application-model#483] opened 2018-06-27 02:49 UTC
for resrouce AWS::Serverless::Api the stageName is a string.
Is it possible to create multile stage in one api section ?
or I need to have two same AWS::Serverless::Api for different stages ?
Thanks.

**Comment by brettstack** [comment] 2018-06-27 03:32
Duplicate of #198. I'll comment over there.

**Closed by brettstack** 2018-06-27 03:32 UTC
