### ISSUE TITLE
Specify api key  with serverless model

### ISSUE THREAD

**Issue by jasondaicoder** [awslabs/serverless-application-model#162] opened 2017-07-24 05:13 UTC
I am trying to specify the api key/usage plan into the serverless template, however I couldn't find any properties for them. Does the serverless model support api key/usage plan for the api gateway? Or we will have to use normal restapi resource instead of the serverless model?

Cheers

Jason

**Comment by sanathkr** [comment] 2017-08-01 19:31
This is not supported yet. You should use normal cloudformation resources until this feature is implemented

**Comment by jfuss** [comment] 2018-01-08 20:14
We created a parent task to track this. Please see #248 for updates.

Closing as duplicate of #248

**Closed by jfuss** 2018-01-08 20:14 UTC
Labels: type/duplicate, type/feature
