### ISSUE TITLE
SSMParameterReadPolicy should accept the complete parameter name

### ISSUE THREAD

**Issue by abstiles** [awslabs/serverless-application-model#1106] opened 2019-08-28 15:31 UTC
**Description:**

The `SSMParameterReadPolicy` template does not assemble the ARN correctly when giving a `ParameterName` which is a real, full parameter name. It includes a duplicate leading slash.

**Steps to reproduce the issue:**
1. Add an `SSMParameterReadPolicy` to a lambda in the SAM CloudFormation template.
2. Give a path to a real parameter (or parameter prefix) as the `ParameterName` such as `ParameterName: /full/parameter/with/path`
3. Deploy the generated template.

**Observed result:**

The "Allow" permissions are granted to a resource that looks like:

`"Resource": "arn:aws:ssm:<region>:<account>:parameter//full/parameter/with/path"` (Note the doubled slash.)

**Expected result:**

The "Allow" permissions are granted to a resource that looks like:

`"Resource": "arn:aws:ssm:<region>:<account>:parameter/full/parameter/with/path"`

**Comment by keetonian** [comment] 2019-09-03 17:44
Duplicate of https://github.com/awslabs/serverless-application-model/issues/1112, will address comments there

**Closed by keetonian** 2019-09-03 17:44 UTC
Labels: type/to-be-triaged
