### ISSUE TITLE
Not able to provision API keys after removal

### ISSUE THREAD

**Issue by MatteoGioioso** [awslabs/serverless-application-model#1223] opened 2019-10-27 03:58 UTC
**Description:**

I have successfully deployed API keys previously, however after I have deleted them from `Api Gateway` console, now I am not able to provision them anymore, the deployment goes smoothly, no error, but when I go and check them through the aws console the screen does't show them

**Steps to reproduce the issue:**
This is my SAM template
```
Resources:
  #API GATEWAY ========================================
  myAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      DefinitionBody:
        swagger: "2.0"
        info:
          title:
            Ref: AWS::StackName
        x-amazon-apigateway-api-key-source: HEADER
        securityDefinitions:
          myAPIKey:
            type: "apiKey"
            name: "x-api-key"
            in: "header"
        paths:
          /path/invocation:
            post:
              responses: {}
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${myFunction.Arn}/invocations
                httpMethod: "POST"
                type: "aws_proxy"
              security:
                - myAPIKey: []

  myAPIKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Enabled: true

  myUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref myAPI
          Stage: !Ref Environment

  myUsagePlankey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref myAPIKey
      KeyType: API_KEY
      UsagePlanId: !Ref myUsagePlan
```

**Observed result:**
No error, the deployment is successful, but the api key are not showing and the usage plan is not connected to any key

**Expected result:**
It should provision the key

**Comment by MatteoGioioso** [comment] 2019-10-27 04:18
Ok, I have managed to provision my key again. I had to deploy a new version of my app without APIkey, UsagePlan and UsagePlanKey. 
After that I had re-deployed my original app including again those resources.
Just wondering, why is that happening? Thanks

**Comment by timoschilling** [comment] 2019-10-28 07:53
I think this is an expected behaviour because of CloudFormation only deploys changes of you stack, it didn't know anything about external changes. CF only applies the changes of your template, so there was only a change for CF as you removed it from your template and a change as you added them again.

**Comment by ShreyaGangishetty** [comment] 2019-11-01 17:29
@timoschilling Thank you for the response. Closing this as it is an expected CloudFormation behavior

**Closed by ShreyaGangishetty** 2019-11-01 17:29 UTC
