### ISSUE TITLE
Is there any way to define the API Gateway cache TTL?

### ISSUE THREAD

**Issue by sgruenheit** [awslabs/serverless-application-model#130] opened 2017-05-09 07:36 UTC
In the resource type AWS::Serverless::Api I'm able to enable the API Gateway caching using
_CacheClusterEnabled: true
CacheClusterSize: "0.5"_

I can't see any possibility to set the cache TTL anywhere - is there any way to do it? Unfortunately the cache is not working without that value and setting it manually is not an option.

Thanks in advance

**Comment by sanathkr** [comment] 2017-06-28 08:10
Interesting. Where do you usually specify the TTL with `AWS::ApiGateway::Stage` resource? In `MethodSettings` property? If so, yes, SAM should support it.

**Comment by sgruenheit** [comment] 2017-06-28 08:22
Thank you for answer. Actually it seems to be defined in the _MethodSetting_ of `AWS::ApiGateway::Stage`.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-stage-methodsetting.html

**Comment by sanathkr** [comment] 2017-06-28 19:07
Yeah, that's how the TTL is defined in API Gateway.

**Comment by sgruenheit** [comment] 2017-06-28 19:20
Yes at least at API level. When using the AWS Console it is configured at stage level (and can be overwritten on method level). Any chance to add it?

![api gateway](https://user-images.githubusercontent.com/24938091/27655903-51e6f0fe-5c47-11e7-8ddb-5c3699487e54.png)

**Comment by sanathkr** [comment] 2017-06-29 16:06
Turns out you can do it with method settings by using */* for path/method combo - http://docs.aws.amazon.com/cli/latest/reference/apigateway/create-stage.html. So yes, we can enable a Stage-wide TTL setting.

All of the `MethodSettings` properties look useful to expose via SAM. How about we simply allow the entire MethodSettings object and you set it to whatever you like?

**Comment by sgruenheit** [comment] 2017-06-30 05:53
That sounds great! And yes I agree with you, the other settings are useful too and could be added as well!

**Comment by Sarceus** [comment] 2017-07-08 15:04
How would I go about to add TTL to each method until Stage-wide TTL is implemented?

**Comment by sanathkr** [comment] 2017-07-09 01:14
@Sarceus  you can't with `AWS::Serverless::Api` resource. You have to fallback to doing it yourself using `AWS::ApiGateway::*`  resources

**Comment by antaltshul** [comment] 2017-07-18 19:56
Just wanted to agree that more control over stage cache and per-method cache settings (or just exposing `MethodSettings` in general) would be a big help in avoiding post-deployment scripts, change sets, or manual adjustment of API settings.

**Comment by StoyanIvanovI** [comment] 2017-12-20 15:12
The fact that this is missing is quite a big showstopper for a lot of implementations. You normally want to use the cache for API Gateway as it is cheap and effective way to increase your performance. I could not get the cache working without setting the TTL to anything. The default value should be 300 but I think SAM might be overriding it to 0 which effectively disables the cache. It almost rendered SAM useless for us. I almost consider it a bug and not a feature request.

**Comment by jfuss** [comment] 2018-01-08 20:23
We created a parent task to track this. Please see #248 for updates.

Closing as duplicate of #248

**Closed by jfuss** 2018-01-08 20:23 UTC
Labels: type/duplicate, type/feature

**Comment by sjain2015** [comment] 2018-11-21 08:58
How to enable api gateway cache ttl using methodSettings ? I am using this in template yaml but it does not work, it is not enabling caching at method level. Any thing missing here. Please help.
          CacheClusterEnabled: true
          CacheClusterSize: "1.6"
          MethodSettings: 
            - ResourcePath: "/*"
              CachingEnabled: true
              CacheTtlInSeconds: 600
              HttpMethod: "GET"

**Comment by mearns** [comment] 2019-05-29 20:56
@sjain2015, try just "/" as the resource path:

```yaml
MethodSettings:
  - ResourcePath: /
    CachingEnabled: true
```
etc.
