### ISSUE TITLE
SAM Local testing doesn't work for source inside a folder

### ISSUE THREAD

**Issue by sharji2322** [awslabs/serverless-application-model#405] opened 2018-04-24 23:59 UTC
**Description:**

I have set up a Lambda-API project using AWS SAM. My directory structure for the code is as follow - 
```
Project
-src
--index.js
-template.yml
-buildspec.yml
```

My template.yml has the following serverless function 
```
  DummyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.helloWorld
      Runtime: nodejs6.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: helloworld
            Method: post
```
This function runs perfectly when I deploy it in AWS. But while using SAM Local I am facing an issue. I get the following error -
 
```
   Unable to import module 'src/index': Error
    at Function.Module._resolveFilename (module.js:469:15)
```
If I move the index.js to the main root folder and change my template.yml to 

```
Project
-index.js
-template.yml
-buildspec.yml
```

```
    Properties:
      Handler: index.helloWorld
```
then I am able to run the api using SAM local. 

I don't want to put all my functions in the same file and I am trying to split my functions and keep them inside src folder.

**Comment by vnktsh** [comment] 2018-04-26 03:18
I'm having the same issue:

```
||→ sam local invoke -t dispatch-service.yaml -e tests/get-test.json DispatchService
2018/04/25 21:53:27 Successfully parsed dispatch-service.yaml
2018/04/25 21:53:27 Connected to Docker 1.35
2018/04/25 21:53:27 Fetching lambci/lambda:python3.6 image for python3.6 runtime...
python3.6: Pulling from lambci/lambda
Digest: sha256:d677f6d0b79468f475b178ab37f33359250f24ed7ce3b0eb249bfc1173dc968b
Status: Image is up to date for lambci/lambda:python3.6
2018/04/25 21:53:28 Invoking dispatch_service.lambda_handler (python3.6)
2018/04/25 21:53:28 Mounting /mnt/c/Users/venkateshv/projects/activemalware/hw/dispatch-service/src as /var/task:ro inside runtime container
START RequestId: 9b8bc4af-ae3c-4993-a2d9-26eef39493db Version: $LATEST
Unable to import module 'dispatch_service': No module named 'dispatch_service'
END RequestId: 9b8bc4af-ae3c-4993-a2d9-26eef39493db
REPORT RequestId: 9b8bc4af-ae3c-4993-a2d9-26eef39493db Duration: 0 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 19 MB

{"errorMessage": "Unable to import module 'dispatch_service'"}
```
Directory structure
```
||→ tree -L 3
.
├── deploy.sh
├── dispatch-service.yaml
├── src
│   ├── dbconnector.py
│   ├── dispatch_service.py
│   ├── lib
│   │   └── psycopg2
│   └── utils.py
├── target
│   └── output_dispatch-service.yaml
└── tests
    └── get-test.json
```

Relevant part in `dispactch-service.yaml`
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: [REDACTED]
Resources:
  DispatchService:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: dispatch_service.lambda_handler
      Runtime: python3.6
      CodeUri: src/
      Description: [REDACTED]
      MemorySize: 128
      Timeout: 10
```

**Comment by jfuss** [comment] 2018-04-27 12:45
This is a sam-local issue not sam (serverless application model). Please move the issue to https://github.com/awslabs/aws-sam-local/issues

Closing as the issue is not meant for this repo

**Closed by jfuss** 2018-04-27 12:45 UTC
