### ISSUE TITLE
Specify Log group name for Functions

### ISSUE THREAD

**Issue by dinvlad** [awslabs/serverless-application-model#92] opened 2017-02-16 21:40 UTC
Would it be possible to override Log group name for each function? Currently, CloudFormation creates one with a random suffix according to the Function's name. I don't mind these suffixes in Function names, however if we delete the stack, the log groups remain there and it gets much harder to navigate them (basically, each stack recreation generates a new set of log groups with the same prefix but a different suffix). I'd prefer to log everything into a single group, but just different streams.

Thanks

**Comment by dinvlad** [comment] 2017-02-17 23:57
I guess this could be solved by specifying a fixed Function name now. Please re-open if someone still needs custom logging (though I don't think this is supported by AWS::Lambda::Function either).

**Comment by kbalakumar** [comment] 2018-03-12 00:59
hi,

I ideally would like to define standards for all log groups, so not able to define the log group for each function or apiGateway is not ideal.

Is there anyway to specific log groups for each of these resources like apiGateway or Lambda function?

Thanks

**Comment by kbalakumar** [comment] 2018-03-12 01:02
btw, how do I reopen this issue? @dinvlad

**Comment by jfuss** [comment] 2018-03-12 14:26
@kbalakumar What do you mean by 'would like to define standards for all log groups'? Are you wanting to control the name of the log group, the retention period, or something else?

**Comment by kbalakumar** [comment] 2018-03-12 18:35
@jfuss yes you are right. The naming and the retention period. Also we may have to retain old versions in some cases, all these scenarios we need to define the log group ourselves. Hope it make sense.

**Comment by dinvlad** [comment] 2018-03-13 00:40
Alas we're using GCP now - feel free to keep this issue open

**Comment by jfuss** [comment] 2018-04-10 13:01
@kbalakumar Naming for Log Groups for Lambda (not sure on Api Gateway) is not supported. This is the current limitation by the service.

Retention period is being handled in #257.

Closing this as a duplicate of #257.

**Closed by jfuss** 2018-04-10 13:01 UTC
